force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeController.cls
public with sharing class EmployeeController {
      @AuraEnabled(cacheable=true)
    public static List<Employee__c> getEmployees()
    {
        List<Employee__c> employeeList =
        [
            SELECT Id,
                   Name,
                   Department__r.Name,
                   Status__c,
                   Salary__c
            FROM Employee__c
        ];

        return employeeList;
    }
}