force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LRA-{0000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EmployeeTriggerHandlerTest.cls
@isTest
public class EmployeeTriggerHandlerTest
{
    @isTest
    static void testInactiveEmployeeLeaveRejection()
    {
        Department__c dept =
            new Department__c(
                Name = 'IT'
            );
        insert dept;

        Employee__c emp =
            new Employee__c(
                Name = 'Ravi',
                Status__c = 'Active',
                Department__c = dept.Id
            );
        insert emp;

        Leave_Request__c leaveReq = new Leave_Request__c(
               
                Employee__c = emp.Id,
                Status__c = 'Pending'
            );
        insert leaveReq;

        Test.startTest();

        emp.Status__c = 'Inactive';
        update emp;

        Test.stopTest();

        Leave_Request__c updatedLeave =
        [
            SELECT Status__c
            FROM Leave_Request__c
            WHERE Id = :leaveReq.Id
        ];

        System.assertEquals(
            'Rejected',
            updatedLeave.Status__c
        );
    }
}